name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true
      - run: hugo --minify
      - uses: aquiladev/ipfs-action@v0.3.1-alpha.2
        id: ipfs-add
        with:
          path: ./public
          service: infura
          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }}
          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }}
      - name: Update DNSLink
        run: npx dnslink-cloudflare -d piped.video -l /ipfs/${{ steps.ipfs-add.outputs.hash }} -r _dnslink.docs
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
